[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.1"

[[constraint]]
  name = "github.com/gofrs/uuid"
  version = "3.2.0"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "1.4.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.2"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  version = "1.1.2"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.25.0"

[prune]
  go-tests = true
  unused-packages = true
